### PR TITLE
Enable developers to source PATH from nodew

### PR DESCRIPTION
**Pull request by stormbeta**
This should allow running `source nodew` and have it inject the project-local node/npm paths into the local shell environment. Uses a bash feature to determine whether script is being executed or sourced, so won't work for non-bash user shells.

I also went ahead and got rid of the explicit default npm version - so you should get the bundled npm version by default for whatever version of node is specified (it can still be overridden to force a downgrade or upgrade).

### CODE REVIEW

**Comment by stormbeta** [comment]
@dansomething, @dwilson6, @joshuawarner32 

Hopefully this should alleviate some of the frustrations with the existing nodew script for local development.

**Comment by joshuawarner32** [comment]
Actually, this doesn't really help me since I pretty much exclusively use fish, instead of bash.  However, don't let me stand in your way.

**Comment by dansomething** [comment]
I do use bash so I'll appreciate the change. lgtm

**Comment by CPWeaver** [comment]
:+1:

**Pull request merged**
